# Project info
site_name: Red Hat Ansible Automation Platform Level 3 for Sales and Technical Sales
site_description: Red Hat Ansible Automation Platform Level 3 for Sales and Technical Sales
site_author: Christopher Bienko (cdbienko@us.ibm.com)
copyright: Copyright &copy; 2022 IBM

# Repository
repo_name: IBM/Ansible-Automation-Platform-L3
#repo_url: https://github.com/IBM/Ansible-Automation-Platform-L3
#edit_uri: edit/master/docs
docs_dir: docs


nav:
  - Introduction: 'index.md'
  - Part 1 - Prerequisites and Provisioning:
    - 'Getting Started': 'Part 1/01 Getting Started.md'
  - Part 2 - Deploy a Virtual Machine via Ansible Automation Platform:
    - 'Deploy a Virtual Machine': 'Part 2/01 Deploy a VM.md'
    - 'Deploy an AIX Partition on PowerVC using Ansible': 'Part 2/02 Deploy an AIX Partition.md'
  - Part 3 - Deploy a WebSphere Application Server instance via Ansible Automation Platform:
    - 'Laying the Groundwork': 'Part 3/01 Laying the Groundwork.md'
    - 'Creating Roles for WAS': 'Part 3/02 Creating Roles for WAS.md'
    - 'Creating the Staging Directory for WAS, Copying Source Files, and Executing the Installer': 'Part 3/03 Staging and Execution.md'
    - 'Creation of a Template': 'Part 3/04 Creating a Template.md'
    - 'Installation of WAS, Creation of a Profile, and Launching the Software': 'Part 3/05 Launching WAS.md'
  - Part 4 - Level 3 Accreditation:
    - 'Business Partner Accreditation': 'Part 4/01 Business Partner Accreditation.md'
    - 'IBM Seller and Technical Seller Accreditation': 'Part 4/02 IBMer Accreditation.md'


theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
    - mkdocs-video
    - macros
    - search

markdown_extensions:
  - sane_lists
  - pymdownx.details
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - attr_list
  - md_in_html
  - def_list
